### ISSUE TITLE
Request: load $PWD/.grutrc

### ISSUE THREAD

**Issue by rileyle** [pcbend/GRUTinizer#116]
... to allow, for example, for the simultaneous use of different histogramming libraries by different processes in the same environment.

add:

  // Load $PWD/.grutrc
  grut_path = Form("%s/.grutrc",getenv("PWD"));
  if(file_exists(grut_path.c_str())){
    gEnv->ReadFile(grut_path.c_str(),kEnvChange);
  }

to the end of the LoadGRUTEnv() method in ./src/grutinizer.cxx

**Comment by Lunderberg** [comment]
Added as of cd4bfa6c2a85aa8120d4ec43a682f0cbd141f1fb
