### ISSUE TITLE
Reading form a zipped file is broken. and it shouldnt be.

### ISSUE THREAD

**Issue by belargej** [pcbend/GRUTinizer#31]
GRizer [0] TRawFileIn f("/mnt/analysis/pecan-2015/e15040/Run0044/Global.dat.gz")
GRizer [1] TGEBEvent event
GRizer [2] f.Read(&event)
(int)(-3)
GRizer [3] f.Read(&event)
(int)0
GRizer [4] f.Read(&event)
(int)0
GRizer [5] f.Read(&event)
(int)0
GRizer [6] 

Also, online tree does not read a zip file

**Comment by Lunderberg** [comment]
Fixed as of 6114583be97d48d8456102f6ed61537bfb7bc18e
