### ISSUE TITLE
Very Unstable

### ISSUE THREAD

**Issue by pcbend** [pcbend/GRUTinizer#34]
Things have become very unstable on the master branch using the analysis account on offload.

There different types of sorting, three different types of near immedent failures:

analysis@nscloffload:~/packages/GRUTinizer$ grutinizer -lq /global/data1a/gretina/e15020_data1a/Run0014/Global.dat 
File: /global/data1a/gretina/e15020_data1a/Run0014/Global.dat:     12.43 MB given  /   7870.72 MB total   =>  6.21 MB/s processed terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted

analysis@nscloffload:~/packages/GRUTinizer$ grutinizer -lg /global/data1a/gretina/e15020_data1a/Run0014/Global.dat 
GRizer [0] terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted

analysis@nscloffload:~/packages/GRUTinizer$ grutinizer -lq /global/data1a/gretina/Q6P1_Superpulse_11_2015/Run0003/Global
Global.dat     GlobalRaw.dat  
analysis@nscloffload:~/packages/GRUTinizer$ grutinizer -lq /global/data1a/gretina/Q6P1_Superpulse_11_2015/Run0003/GlobalRaw.dat 
File: /global/data1a/gretina/Q6P1_Superpulse_11_2015/Run0003/GlobalRaw.dat:     19.91 MB given  /   3314.44 MB total   =>  9.95 MB/s processed **\* Error in `grutinizer': double free or corruption (!prev): 0x00007f6114002af0 ***

**Comment by Lunderberg** [comment]
Stability increased as of 125d613b8d25e77e150081e8a4f93312ecdb5f79
