### ISSUE TITLE
TRawFileIn Read

### ISSUE THREAD

**Issue by belargej** [pcbend/GRUTinizer#53]
When trying to use Read for a TRawFileIn in a compile-able code i am getting an error from the compiler that says : 

fasttree.cxx:26:10: error: request for member 'Read' is ambiguous
In file included from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/include/TNamed.h:26:0,
                 from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/include/TBranch.h:28,
                 from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/include/TTree.h:30,
                 from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/include/TChain.h:25,
                 from /user/belarge/Programs/GRUTinizer/include/TGRUTint.h:14,
                 from fasttree.cxx:8:
/mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/include/TObject.h:145:24: error: candidates are: virtual Int_t TObject::Read(const char_)
In file included from fasttree.cxx:9:0:
/user/belarge/Programs/GRUTinizer/include/TRawSource.h:57:7: error:                 int TRawEventSource::Read(TRawEvent_)
/user/belarge/Programs/GRUTinizer/include/TRawSource.h:55:7: error:                 int TRawEventSource::Read(TRawEvent&)

**Comment by pcbend** [comment]
fixed with commit #76ccb0b
