### ISSUE TITLE
Running multiple instance of grutinizer simultaneously

### ISSUE THREAD

**Issue by Lunderberg** [pcbend/GRUTinizer#56]
I have a build script that launches one or more grutinizer instance at a time.  Starting one, everything works fine.  Starting more than one, the loops terminate almost immediately.

**Comment by pcbend** [comment]
Multiple as in started more than one bash session each containing a grut?

**Comment by Lunderberg** [comment]
Yup.  It was done using make, but each grut was in an entirely separate process.  I haven't had time to investigate it yet.  When I ran a single instance of grutinizer at a time, processing a data file ran to completion.  When I ran with "-j2", to launch two instances, the first file runs to completion, but the second stops almost immediately.

**Comment by Lunderberg** [comment]
Closed as of 60d5118d47ee39ada3b1e668668e65a1e50187a7.  ROOT was trying to read on stdin, which gave EOF when there were multiple processes being started.
